# Generated by Django 5.2.7 on 2025-11-22 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cabana_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabana',
            name='imagen_url',
        ),
        migrations.CreateModel(
            name='CabanaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cabanas/images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.cabana')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
