# Generated by Django 5.2.7 on 2025-11-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cabana_imagen_url_cabanaimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Admin'), ('deshabilitado', 'Deshabilitado')], default='cliente', max_length=15),
        ),
    ]
